### ISSUE TITLE
️🛠 - Fix claim finder errors if value on account index 1+

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#1048]
### Task description

Claim finder currently errors if you have funds that need claiming on the second or higher account index.
![Screenshot 2023-10-10 at 13 01 47](https://github.com/bloomwalletio/bloom/assets/89913787/b0cb915c-5029-4f08-b8dc-97225f0aefdc)

### Requirements

- Find and fix error

**Comment by Tuditi** [comment]
https://github.com/iotaledger/firefly/commit/5a390e85dd034fa430cc57e8c44ad767d627ca03

**Comment by Tuditi** [comment]
Not necessarily related to this, but we should still check it: https://github.com/iotaledger/firefly/commit/6ffad619266e4945a4a3364edbd07d9c9c76e808
