### ISSUE TITLE
️🛠 - Fix MacOS notarization

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#1064]
### Task description

MacOS installer needs to be notarized after signing the app, so that apple gatekeeper does not block access. You can not simply sign the app, and sign the installer. You need to use electron notarization to take care of this. The code exists but we seem to have refactored since Firefly and its failing for some reason.

### Requirements

Fix - notarize app

**Comment by Tuditi** [comment]
https://github.com/bloomwalletio/bloom/pull/1068
