### ISSUE TITLE
🐞 - (UX) Windows that require lot of writing effort SHOULDN't be easily unclickable

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#1076]
### Task description

I just lost all the NFT minting details/description etc because i missclicked outside the “MINT NFT” window and window got closed.

Possible fixes:
1. Do not erase the window content after unclick so when we click again, all the boxes are filled with previous data
2. Add “Do you want to exit? All NFT details/token details will be lost” popup with Confirm button
![image](https://github.com/bloomwalletio/bloom/assets/37661351/e57a3df7-c20e-41ec-ac30-23b55eddd00f)

**Comment by jeeanribeiro** [comment]
We have not yet agreed how to move on with the implementation of the UX of it

**Comment by jeeanribeiro** [comment]
Minting NFT and Native Token flows will be redone
