### ISSUE TITLE
🐞 - Improve scrolling in transactions

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#1078]
### Task description

When scrolling in transactions, especially when going fast, they disappear completely or they are jerking. See video!

https://github.com/bloomwalletio/bloom/assets/37661351/b207efa6-d908-433e-9ade-a911100edd1c

**Comment by MarkNerdi** [comment]
Could be fixed with the fixed elements height in https://github.com/bloomwalletio/bloom/pull/1147 and reduced icon size in https://github.com/bloomwalletio/bloom/pull/1159

**Comment by nicole-obrien** [comment]
Is this still an issue?
