### ISSUE TITLE
:lady_beetle:  - Insufficient Funds when sending transaction.

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#1079]
### Task description

Sending with Ledger/Stronghold results in an insufficient fund error if you return to the confirm pop-up when sending a layer 1 transaction.

Steps to reproduce:
With Stronghold profile

1. Lock Stronghold
2. Send all your SMR funds on L1
3. Input Password
4. Confirm Page

![image](https://github.com/bloomwalletio/bloom/assets/37661351/64f32502-df9c-4258-a3ae-9d10026f027b)
![image](https://github.com/bloomwalletio/bloom/assets/37661351/bfa3cab3-6cf8-4971-8045-702b65cd56c7)

----------------------------------------------------------------------------------------

Not sure the steps that caused it so I’ll walk through my setup.

1. Created new profile
2. Sent 10 SMR from Metamask to this new profile’s ShimmerEVM
3. Converted max amount from ShimmerEVM side to Shimmer side (resulted in like 9.95641SMR)
4. Sent 5 SMR from Shimmer Network back to ShimmerEVM
5. Error popped up insufficient funds 0/5027013 available
6. Navigated away to settings and then error log to look at error
7. Went back to home and the balances for both Shimmer Network and EVM had updated.

**Comment by Tuditi** [comment]
Closes this issue: https://github.com/bloomwalletio/bloom/pull/1086
