### ISSUE TITLE
🐞 - Wallet becomes unresponsive after deletion of profile

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#1091]
### Task description

I deleted a profile. After the deletion the main page with the profile overview appears but I can´t click anything. The app becomes unresponsive.

**Comment by MarkNerdi** [comment]
Cannot reproduce this. I deleted all my profiles, as i suspected that its related to the deletion of the last profile, but it wasnt

**Comment by maxwellmattryan** [comment]
@MarkNerdi Tried reproducing this as well, but no luck. I suppose we just keep an eye out for it while we continue releasing and testing.
