### ISSUE TITLE
:lady_beetle: - Initial balance after backup wrong

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1100]
### Task description

After backup with stronghold the initial balance summary in the activity tab is not correct. Either the initial balance summary should be the first activity. Then 0 SMR is correct. If the initial balance summary is after some transactions it should show the actual available amount. In the screenshot below it would be 850 SMR.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/c5e10b00-5cd2-4845-bbe1-2097e039be20)

**Comment by maxwellmattryan** [comment]
If there's already a history then I'm thinking we don't need to show any initial balance at all? :thinking:

**Comment by Tuditi** [comment]
Exclude initial balance activity if 0.
