### ISSUE TITLE
️🛠 - Fix runtime error if Ledger time-out is reached.

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1167]
### Task description

If the ledger is allowed to time-out, there is a runtime error. We should fix this.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/4a2152be-ae5f-43f6-ab3e-187986a451cb)

### Requirements

TBD

**Comment by maxwellmattryan** [comment]
It doesn't quite help having the error in German :joy:

**Comment by Tuditi** [comment]
> It doesn't quite help having the error in German 😂

:de: :de: 

The translation for `Your Ledger device timed out.` taken from en.json.
