### ISSUE TITLE
️🛠 - Fix scrollbar on Verification Pop-up template

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1230]
### Task description

![image](https://github.com/bloomwalletio/bloom/assets/45079109/c537f608-6054-49d2-a81d-030d01349ec8)

**Comment by nicole-obrien** [comment]
Why is the popup so tall? Can we addd the scroll bar to inner templates? Also I think the ledger illustration was made shorter in the latest designs

**Comment by Tuditi** [comment]
The size was different. I tried adding an inner scroll bar, but it broke other popups and the behavior was a bit weird. (e.g. the entire slot was moving instead of only the table). I think we have to asses on a per need basis which part of the pop-up we want to make scrollable.
