### ISSUE TITLE
️🛠 - Fix L2 -> L1 metadata decoding

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1264]
### Task description

L2 -> L1 Metadata encoding is currently broken:

![image](https://github.com/bloomwalletio/bloom/assets/45079109/509fe6aa-c578-4a12-90a4-a7f532ee3dfa)

### Requirements

- [ ] Metadata should show up as a JSON.
- [ ] Investigate whether activity is correct.

**Comment by Tuditi** [comment]
This is not a blocker for early access. The WASP node attaches this metadata, so it's normal that it isn't interpreted. Firefly doesn't decode it either.

We need to ask Wasp team what this metadata means.

**Comment by nicole-obrien** [comment]
In turns out the metadata is not useful at all at the moment so we wouldn't be able to sow anything worthy to the user
