### ISSUE TITLE
️🛠 - Cleanup `desktop` package folder

### ISSUE THREAD

**Issue by maxwellmattryan** [bloomwalletio/bloom#135]
### Description

The desktop folder is a bit unorganized and could use some love.

:no_entry_sign: Blocked until TS refactor is complete for Electron code.

### Requirements

- [x] Add `src/` directory
    - [x] Should contain `components`, `electron`, `features`, `lib`, and `views`

### Checklist

- [X] I have linked the correct milestone and/or project(s)
- [X] I have added the appropriate labels
- [X] I have assigned this task to the correct people

**Comment by Tuditi** [comment]
Blocked by https://github.com/bloomwalletio/bloom/issues/165
