### ISSUE TITLE
️🛠 - Investigate unfullfillable requirement error.

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1358]
### Task description

Sometimes the following issue is thrown from an account when sending from L1:

`unfulfillable requirement Sender(Ed25519Address(0xae31504e6bbcdc0429cf2f02cc2ec13f70516f60cbce688415b9f9d65622ecb1))`

Semantic validation of the transaction feature:
![image](https://github.com/bloomwalletio/bloom/assets/45079109/5065d7ec-4957-4d21-9f89-e664c62d4af8)

**Comment by nicole-obrien** [comment]
Unable to reproduce or have this error reported for a while so we will close for now
