### ISSUE TITLE
️🛠 - Limit amount of decimals on Activity tab

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#1384]
### Task description

A user reported that most ERC20 tokens have 18 decimal places. Displaying all of them in the activity list isn't useful, so it can be truncated

![image](https://github.com/bloomwalletio/bloom/assets/37661351/ade87482-6174-4106-ad55-00f61cd21175)

**Comment by nicole-obrien** [comment]
we should now simplify the use of the formatting functions, likely only need once now where we can pass in a parameters for number of decimals to display etc
