### ISSUE TITLE
🐞 - Cannot read properties of null (reading 'webContents')

### ISSUE THREAD

**Issue by DaZRool** [bloomwalletio/bloom#1385]
### Version

0.1.0

### Description

Did nothing. Error just popped up

### Expected behaviour

-

### Actual behaviour

-

### Can the issue reliably be reproduced?

No

### Crash Status

Application closed

### Error Messages

App Version: 0.1.0

platform: macOS
platformVersion: 14.1
platformArchitecture: x64
cpuCount: 10
totalMem: 16384.0 MB
freeMem: 23.3 MB

Error Type: [Main Context] Unhandled Error

Error: Cannot read properties of null (reading 'webContents')

### Error Logs

```shell
no logs
```

### Profile Type

Software (Stronghold)

### Operating System

Mac

### Diagnostics

```shell
Version: 0.1.0
Language: en
Currency: usd
Node list: https://api.shimmer.network,https://shimmer-node.tanglebay.com
Platform: macOS
Platform Version: 14.1
Platform Architecture: x64
CPU Count: 10
Total Memory: 16384.0 MB
Free Memory: 12.6 MB
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
Hello @DaZRool !

Do you still have this issue in latest versions?

**Comment by DaZRool** [comment]
hey,

I haven't noticed anything so far.

greats
