### ISSUE TITLE
️🛠 - Add `RemoveNetworkDrawer`

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#146]
### Description

This view displays when the user clicks "Remove chain" from the ChainActionsMenuModal.

### Requirements

TBD

### Checklist

- [X] I have linked the correct milestone and/or project(s)
- [X] I have added the appropriate labels
- [ ] I have assigned this task to the correct people

**Comment by MarkNerdi** [comment]
implemented in https://github.com/bloomwalletio/bloom/pull/2736
