### ISSUE TITLE
️🛠 - Align how L2 balance looks with L1 balance on profile creation

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1481]
### Task description

L1 & L2 account balance should look the same when a user creates a profile. This issue is mitigated upon login & logout, but it should be right on first login.

This also results in users not receiving their Shimmer on start-up.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/0ba4e09b-364e-4f6c-927c-dcc7d5d42268)

### Requirements

TBD

**Comment by nicole-obrien** [comment]
I think this was fixed in the 0.1.1 branch that was merged in #1461

**Comment by Tuditi** [comment]
I can confirm it's fixed
