### ISSUE TITLE
️🛠 - Add Bloom to RainbowKit

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#1551]

**Comment by MarkNerdi** [comment]
PR open: https://github.com/rainbow-me/rainbowkit/pull/1645

**Comment by MarkNerdi** [comment]
PR has been merged. Now waiting for next release

**Comment by nicole-obrien** [comment]
Merged in: https://github.com/rainbow-me/rainbowkit/pull/1784
