### ISSUE TITLE
️🛠 - Fix activities for ERC721 NFTs

### ISSUE THREAD

**Issue by maxwellmattryan** [bloomwalletio/bloom#1577]
### Task description

When first querying and loading ERC721 NFTs into Bloom, the corresponding activity is incorrect. At the very least, it should **NOT** say sent.

![Screenshot from 2023-12-06 15-47-14](https://github.com/bloomwalletio/bloom/assets/44885822/b06e6858-5301-4b57-abad-93809b19a472)
![Screenshot from 2023-12-06 15-47-23](https://github.com/bloomwalletio/bloom/assets/44885822/db4c220d-f217-43f2-a844-f37f7a72e265)

### Requirements

_TBD_

**Comment by nicole-obrien** [comment]
So I( am starting to question whether we need an initial balance when a profile is restored, they are quite confusing and if you have a lot of tokens then you have a lot of pointless balances. Can we hide these?
