### ISSUE TITLE
Bloom error downloading new update 0.1.2🐞 - App Version: 0.1.1  platform: win32 platformVersion: 10.0.19045 platformArchitecture: x64 cpuCount: 4 totalMem: 3981.7 MB freeMem: 672.8 MB  Error Type: [Main Context] Unhandled Error  Error: Command failed: chcp 65001 >NUL & powershell.exe -NoProfile -NonInteractive -InputFormat None -Command "Get-AuthenticodeSignature -LiteralPath 'C:\Users\Asus\AppData\Local\desktop-updater\pending\temp-bloom-desktop-0.1.2.exe' | ConvertTo-Json -Compress"

### ISSUE THREAD

**Issue by bazchap** [bloomwalletio/bloom#1592]
### Version

0.1.1

### Description

App Version: 0.1.1

platform: win32
platformVersion: 10.0.19045
platformArchitecture: x64
cpuCount: 4
totalMem: 3981.7 MB
freeMem: 672.8 MB

Error Type: [Main Context] Unhandled Error

Error: Command failed: chcp 65001 >NUL & powershell.exe -NoProfile -NonInteractive -InputFormat None -Command "Get-AuthenticodeSignature -LiteralPath 'C:\Users\Asus\AppData\Local\desktop-updater\pending\temp-bloom-desktop-0.1.2.exe' | ConvertTo-Json -Compress"

### Expected behaviour

expected new version to load & execute

### Actual behaviour

didnt load & i received error log which ive supplied above

### Can the issue reliably be reproduced?

No

### Crash Status

None of the above

### Error Messages

App Version: 0.1.1

platform: win32
platformVersion: 10.0.19045
platformArchitecture: x64
cpuCount: 4
totalMem: 3981.7 MB
freeMem: 672.8 MB

Error Type: [Main Context] Unhandled Error

Error: Command failed: chcp 65001 >NUL & powershell.exe -NoProfile -NonInteractive -InputFormat None -Command "Get-AuthenticodeSignature -LiteralPath 'C:\Users\Asus\AppData\Local\desktop-updater\pending\temp-bloom-desktop-0.1.2.exe' | ConvertTo-Json -Compress"

### Error Logs

```shell
App Version: 0.1.1

platform: win32
platformVersion: 10.0.19045
platformArchitecture: x64
cpuCount: 4
totalMem: 3981.7 MB
freeMem: 672.8 MB

Error Type: [Main Context] Unhandled Error

Error: Command failed: chcp 65001 >NUL & powershell.exe -NoProfile -NonInteractive -InputFormat None -Command "Get-AuthenticodeSignature -LiteralPath 'C:\Users\Asus\AppData\Local\desktop-updater\pending\temp-bloom-desktop-0.1.2.exe' | ConvertTo-Json -Compress"
```

### Profile Type

Software (Stronghold)

### Operating System

Windows

### Diagnostics

```shell
Version: 0.1.1
Language: en
Currency: usd
Node list: https://api.shimmer.network,https://shimmer-node.tanglebay.com
Platform: win32
Platform Version: 10.0.19045
Platform Architecture: x64
CPU Count: 4
Total Memory: 3981.7 MB
Free Memory: 491.6 MB
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
Hey @bazchap , does this error still occur for you? We haven't had any reports of Windows user with this error for a while now.

**Comment by bazchap** [comment]
Seems ok now, thanks. 🙂 kind regards

**Comment by Tuditi** [comment]
Thanks for checking! I will close this issue now. Feel free to reopen if the issue appears again. Cheers!
