### ISSUE TITLE
No matching key on first startup after update🐞 - 

### ISSUE THREAD

**Issue by t00k** [bloomwalletio/bloom#1636]
### Version

0.1.4-alpha-1

### Description

After updating to latest version of alpha this error occured. Could close it down and continue as nothing happened. Did not show after this.

### Expected behaviour

Get to login-screen without error message.

### Actual behaviour

This error emssage popped up.

### Can the issue reliably be reproduced?

No

### Crash Status

None of the above

### Error Messages

Yes. 
![updatetolatesterrormessageBloom](https://github.com/bloomwalletio/bloom/assets/49842330/69e3e98a-222a-4bf9-a4d7-123caf2bb366)

### Profile Type

Software (Stronghold)

### Operating System

Windows

### Diagnostics

```shell
See screenshot above, did not copy.
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
Fixed in latest version, please reopen if the issue still exists
