### ISSUE TITLE
🐞 - On the final account creation screen, the text isn't centered when it's too long (translated)

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [bloomwalletio/bloom#1643]
### Version

0.1.4-alpha-1

### Description

On the final account creation screen, the text isn't centered when it's too long (translated)

It is okay on original English string.
![YKx6MxM](https://github.com/bloomwalletio/bloom/assets/35224101/fe19948b-ce3c-483e-a7a9-00815b83349b)

### Expected behaviour

x

### Actual behaviour

x

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

x

### Crash Status

None of the above

### Error Messages

x

### Profile Type

Software (Stronghold)

### Operating System

Windows

### Diagnostics

```shell
x
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
Fixed in #1647
