### ISSUE TITLE
🐞 - Crash after Generating SMR EVM address with Ledger

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [bloomwalletio/bloom#1644]
### Version

0.1.4-alpha-1

### Description

Crash after Generating SMR EVM address with Ledger

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Generate Shimmer EVM address
2. It prompts you to open ETH app on your ledger
3. Open it
4. It shows the address on the right panel
5. Click to copy it
6. Error window appears with below error (we can't close it) the app behind it works

### Crash Status
![ntMgJNm](https://github.com/bloomwalletio/bloom/assets/35224101/d75cd899-957e-4284-9d6b-244326f0867f)

### Error Messages

App Version: 0.1.4-alpha-1

platform: win32
platformVersion: 10.0.22631
platformArchitecture: x64
cpuCount: 24
totalMem: 32679.7 MB
freeMem: 24018.7 MB

Error Type: [Preload Context] Unhandled Rejection

Error: An object could not be cloned.

### Profile Type

Hardware (Ledger)

### Operating System

Windows

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
This error always comes together with the error in  attached image.    This is caused if the `Copied` tooltip is open and then the drawer is closed. This is default browser behaviour as we have multiple animations happening at the same time, apparently too many in this instant 
![image](https://github.com/bloomwalletio/bloom/assets/37661351/7b37ceed-a8c1-40a8-b7ea-db316d2c5ab3)

**Comment by UmbahaSpodPaha** [comment]
I wanted to confirm this bug is still present on 0.1.4 alpha 3
What more, it seems we can't close the crash window but it's actually possible with ALT+F4 combination
**Adding an close button to the crash window would help as well.**
