### ISSUE TITLE
🛠 - Improve transaction confirmation after Stronghold password pop-up

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1679]
### Task description

If the user has to enter the SH password, then some of the information is lacking. This should be improved.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/5afce4db-07b5-426e-a621-3961b9215f46)

### Requirements

TBD

**Comment by Tuditi** [comment]
Might be fixed by https://github.com/bloomwalletio/bloom/pull/1614

**Comment by nicole-obrien** [comment]
We can now implement this as 1614 has been merged in
