### ISSUE TITLE
️🛠 - Impossible to restore Stronghold if it gets locked. 

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#173]
### Task description

Duplicate of: https://github.com/iotaledger/firefly/issues/4823

Fixed in: https://github.com/iotaledger/firefly/pull/7047

### Requirements

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
I checked and stronghold does not auto lock unless we set a stronghold timeout. So I don't think that fix is doing anything, except prolonging how long we need the password in stores. We can or should check stronghold before calling login function, like we do with ledger.
