### ISSUE TITLE
️🛠 - Handle Transak events

### ISSUE THREAD

**Issue by jeeanribeiro** [bloomwalletio/bloom#1755]
### Task description

Transak has some events that are useful to be displayed to the user, e.g. the successful transaction could display a success toast notification

Available events:

```
TRANSAK_WIDGET_INITIALISED,
TRANSAK_WIDGET_OPEN,
TRANSAK_WIDGET_CLOSE_REQUEST,
TRANSAK_WIDGET_CLOSE,
TRANSAK_ORDER_CREATED,
TRANSAK_ORDER_CANCELLED,
TRANSAK_ORDER_FAILED,
TRANSAK_ORDER_SUCCESSFUL,
TRANSAK_WALLET_REDIRECTION
```

**Comment by nicole-obrien** [comment]
Just add notifications for the appropriate events for now until we have some design inout
