### ISSUE TITLE
️🛠 - Integrate function for transferring ERC20 tokens

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#20]
### Description

With the function to transfer ERC20 tokens created, it can be integrated within an actual send flow.

### Requirements

TBD

### Checklist

- [X] I have linked the correct milestone and/or project(s)
- [X] I have added the appropriate labels
- [x] I have assigned this task to the correct people

**Comment by Tuditi** [comment]
Potentially addressed in https://github.com/bloomwalletio/bloom/pull/129

**Comment by MarkNerdi** [comment]
Closed in https://github.com/bloomwalletio/bloom/pull/129
