### ISSUE TITLE
️🛠 - Set-up snyk

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#205]
### Task description

Something is wrong with the snyk CI. We probably have to add an API key to the repository, but it might need some more investigating

https://github.com/bloomwalletio/bloom/actions/runs/5452570274/jobs/9920253277

### Requirements

- [ ] Snyk workflow shows vulnerable dependencies.
- [ ] Add documentation to [SOP](https://www.notion.so/bloom-labs/SOP-Dependency-Management-08dbe7d05b82431f90389883772d2fd1)

**Comment by nicole-obrien** [comment]
Do we think we need snyk, when we have dependabot?

**Comment by Tuditi** [comment]
Snyk offers better and deeper analysis than dependabot and it is easy to set up. We should definitely work on adding this before we go live.

**Comment by Tuditi** [comment]
As discussed we will wait until we open-source the code to integrate snyk, since it's free in that case.
