### ISSUE TITLE
️🛠 - App crash on NFT blockscout fetch

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#2089]
### Task description

On collections we try to check the owner for every NFT in it. Somehow in `checkForUntrackedNfts` line `47` I got an ERC20 token with a value of 2*10^18. So we try to create a 2*10^18 long array, which crashes the app.

Task: find out why an ERC20 token is there and prevent that.

**Comment by nicole-obrien** [comment]
Not encountered this again, closing for now
