### ISSUE TITLE
️🛠 - Create function for unwrapping base / IRC30 tokens

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#22]
### Description

Implement function to unwrap native tokens and base coin from the core contracts using Ledger. This interacts with the `withdraw()` function similarly to `transferAllowanceTo`.

Reference: https://wiki.iota.org/shimmer/smart-contracts/guide/core_concepts/core_contracts/accounts#withdraw

### Requirements

- [x] Unwrap base tokens
- [x] Unwrap IRC30 tokens
- [x] Organize interfaces and types 
    - [x] Use existing ones where possible 

### Checklist

- [X] I have linked the correct milestone and/or project(s)
- [X] I have added the appropriate labels
- [x] I have assigned this task to the correct people

**Comment by maxwellmattryan** [comment]
According to the specification link, there is this:
> A call to withdraw means that a L1 output will be created. Because of this, the withdrawn amount must be able to cover the L1 storage deposit. Otherwise, it will fail.

We need to make sure we can estimate whether a withdraw amount is high enough to cover SD.

**Comment by maxwellmattryan** [comment]
The [`evm-toolkit`](https://github.com/iotaledger/evm-toolkit/blob/main/src/lib/iscmagic/iscmagic.ts#L105C16-L105C24) ref. is also helpful :pray:
