### ISSUE TITLE
🐞 - During sending SOON to stake on SOONAVERSE got this error

### ISSUE THREAD

**Issue by PuckStar** [bloomwalletio/bloom#2205]
### Version

0.1.11

### Description

I was sending SOON tokens to SOONAVERSE for staking there. Then this popup error came up.
The sending of tokens went through though. So all is fine and I just restarted Bloom.

### Expected behaviour

no error popup? :)

### Actual behaviour

error message

### Can the issue reliably be reproduced?

Yes

### Crash Status

Non-responsive

### Error Messages

App Version: 0.1.11

platform: win32
platformVersion: 10.0.19045
platformArchitecture: x64
cpuCount: 16
totalMem: 98229.5 MB
freeMem: 82235.7 MB

Error Type: [Render Context] Unhandled Rejection

Internal error: arithmetic operation overflow

   0: napi_register_module_v1
   1: napi_register_module_v1
   2: <unknown>
   3: <unknown>
   4: napi_register_module_v1
   5: napi_register_module_v1
   6: napi_register_module_v1
   7: napi_register_module_v1
   8: napi_register_module_v1
   9: BaseThreadInitThunk
  10: RtlUserThreadStart

### Error Logs

```shell
I don't think these were related to the error I got but this is the latest in the error log:
Tue, 26 Mar 2024 20:27:36 GMT
error: `node error: The requested data https://shimmer-node.tanglebay.com/api/participation/v1/events/0xaa76a719998a4c37c7b70ce40d75f7256789264f9962c327798c25c6eb1c48c7 was not found.`

Tue, 26 Mar 2024 20:17:45 GMT
error: `node error: The requested data https://shimmer-node.tanglebay.com/api/participation/v1/events/0xaa76a719998a4c37c7b70ce40d75f7256789264f9962c327798c25c6eb1c48c7 was not found.`
```

### Profile Type

Software (Stronghold)

### Operating System

Windows

### Diagnostics

```shell
Version: 0.1.11
Language: en
Currency: usd
Node list: https://api.shimmer.network,https://shimmer-node.tanglebay.com
Platform: win32
Platform Version: 10.0.19045
Platform Architecture: x64
CPU Count: 16
Total Memory: 98229.5 MB
Free Memory: 81882.6 MB
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Likely a third party issue with tanglebay that has since been resolved
