### ISSUE TITLE
️🛠 - Add warning to scam NFTs

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#2276]
### Task description

We want to warn users if we find a scam nft. This can be done in a few ways, comparing the url against a scam list. Using regex on the name and description to detect key words etc.

### Requirements

- Detect if NFT is potential scam.
- Mark as potential scam
- Do not download the nft
- Hide by default

**Comment by Tuditi** [comment]
Blocked by the capability ot hide/unhide NFTs https://github.com/bloomwalletio/bloom/issues/45
