### ISSUE TITLE
️🛠 - Investigate if it's possible to replace the ETH ticker on the ledger app

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#247]
### Task description

Atm sending L1 -> L2 transactions with base tokens results in the ETH ticker showing up instead of the SMR ticker within the Ethereum app. This could confuse users, since there is multiple order of magnitudes difference between the 2. Let's investigate whether we can replace this in the ledger app and see how other ecosystems solve this issue.

### Requirements

- [ ] Have a clear strategy on how to tackle showing the correct ticker.

**Comment by nicole-obrien** [comment]
Potentially a UX issue to improve the verification popup to show the user that it will show ETH on the device

**Comment by Tuditi** [comment]
An alternative route is to clone the Ethereum app: https://developers.ledger.com/docs/embedded-app/clone-intro/

**Comment by nicole-obrien** [comment]
Don't think its possible or worth the effort at the moment
