### ISSUE TITLE
🐞 - Wallet switching by entering pincode fast fails

### ISSUE THREAD

**Issue by JannemanDev** [bloomwalletio/bloom#2482]
### Version

1.0.2 production

### Description

If you switch wallets by entering the pincode fast... I did this by holding down 0... as my pincode is 00000. Keep it down even after all digits are entered.
If you just enter the pincode slowly like normal it works ok.

Also if just start Bloom and enter a wallet for the first time by entering the pincode fast like above the error happens!

This bug is still happening from versions back around 19 january 2024 and maybe even earlier, can't remember.
![Screenshot 2024-05-13 125456](https://github.com/bloomwalletio/bloom/assets/13236774/c054ee9a-2202-4bdd-b452-90685edc4a34)
![Screenshot 2024-05-13 125437](https://github.com/bloomwalletio/bloom/assets/13236774/208f01f6-222a-4015-85d5-bfd819aa94d0)

### Expected behaviour

correct opening/switching new wallet without error

### Actual behaviour

error is shown and you can't open/switch wallet

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

see description

### Crash Status

None of the above

### Error Messages

see description

### Profile Type

Software (Stronghold)

### Operating System

Windows

### Diagnostics

```shell
Version: 1.0.2
Language: en
Currency: undefined
Node list: undefined
Platform: win32
Platform Version: 10.0.22631
Platform Architecture: x64
CPU Count: 2
Total Memory: 8190.9 MB
Free Memory: 4253.1 MB
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JannemanDev** [comment]
I retried above on the latest v1.0.3 and I could not reproduce, so I guess it got fixed??
I think for now you can close this issue. In future versions I will keep testing above and will report back if error popups again.

**Comment by jeeanribeiro** [comment]
> I retried above on the latest v1.0.3 and I could not reproduce, so I guess it got fixed?? I think for now you can close this issue. In future versions I will keep testing above and will report back if error popups again.

Thank you for reporting @JannemanDev 🙏
