### ISSUE TITLE
🐞 - Updating from 1.0.2 to 1.0.3 on Windows failed (only on first try)

### ISSUE THREAD

**Issue by JannemanDev** [bloomwalletio/bloom#2539]
### Version

1.0.2

### Description

Start v1.0.2 and got an update notification and tried updating. Waiting for download to finish... at the end of progress I got this error:
```
App Version: 1.0.2

platform: win32
platformVersion: 10.0.22631
platformArchitecture: x64
cpuCount: 2
totalMem: 8190.9 MB
freeMem: 3273.2 MB

Error Type: [Main Context] Unhandled Error

Error: Command failed: chcp 65001 >NUL & powershell.exe -NoProfile -NonInteractive -InputFormat None -Command "Get-AuthenticodeSignature -LiteralPath 'C:\Users\Jan\AppData\Local\desktop-updater\pending\temp-bloom-desktop-1.0.3.exe' | ConvertTo-Json -Compress"
```

I closed Bloom and restarted Bloom, got again update notification and tried again downloaden and updating and now it did work. Now using v1.0.3

### Expected behaviour

Updating on first try should work.

### Actual behaviour

Error popups, see description.

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

see description

### Crash Status

None of the above

### Error Messages

App Version: 1.0.2

platform: win32
platformVersion: 10.0.22631
platformArchitecture: x64
cpuCount: 2
totalMem: 8190.9 MB
freeMem: 3273.2 MB

Error Type: [Main Context] Unhandled Error

Error: Command failed: chcp 65001 >NUL & powershell.exe -NoProfile -NonInteractive -InputFormat None -Command "Get-AuthenticodeSignature -LiteralPath 'C:\Users\Jan\AppData\Local\desktop-updater\pending\temp-bloom-desktop-1.0.3.exe' | ConvertTo-Json -Compress"

### Error Logs

```shell
was empty?!
```

### Profile Type

Software (Stronghold)

### Operating System

Windows

### Diagnostics

```shell
Version: 1.0.3
Language: en
Currency: undefined
Node list: undefined
Platform: win32
Platform Version: 10.0.22631
Platform Architecture: x64
CPU Count: 2
Total Memory: 8190.9 MB
Free Memory: 3414.3 MB
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
Hello @JannemanDev 

I couldn't reproduce this issue, also we didn't got any more reports about it, must be an edge case but we will still keep an eye on it, lets wait and see if someone else gets the same error or if the issue persists on the next update.

Thank you for reporting!
