### ISSUE TITLE
🐞 - Memory Error 

### ISSUE THREAD

**Issue by pablo-hp** [bloomwalletio/bloom#2542]
### Version

1.0.0 a 1.0.3

### Description

App Version: 1.0.3

platform: win32
platformVersion: 10.0.22621
platformArchitecture: x64
cpuCount: 4
totalMem: 6018.0 MB
freeMem: 839.3 MB

Error Type: [Render Context] Unhandled Rejection

Error: Error invoking remote method 'keychain-set': Error: Não há recursos de memória disponíveis suficientes para processar este comando.

### Expected behaviour

After entering a wallet's restore phrase, the error appears.

### Actual behaviour

After entering a wallet's restore phrase, the error appears.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

install
open
Begin setup
skip third party wallets 
Iota Mainnet
Restore Profile
Recovery phrase
Secure your profile
Find your recovered accounts
Give your profile a name
Add a PIN number
ERROR

### Crash Status

None of the above

### Error Messages

App Version: 1.0.3

platform: win32
platformVersion: 10.0.22621
platformArchitecture: x64
cpuCount: 4
totalMem: 6018.0 MB
freeMem: 839.3 MB

Error Type: [Render Context] Unhandled Rejection

Error: Error invoking remote method 'keychain-set': Error: Não há recursos de memória disponíveis suficientes para processar este comando.

### Profile Type

Software (Stronghold)

### Operating System

Windows

### Diagnostics

```shell
App Version: 1.0.3

platform: win32
platformVersion: 10.0.22621
platformArchitecture: x64
cpuCount: 4
totalMem: 6018.0 MB
freeMem: 839.3 MB

Error Type: [Render Context] Unhandled Rejection

Error: Error invoking remote method 'keychain-set': Error: Não há recursos de memória disponíveis suficientes para processar este comando.
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
> ### Version
> 1.0.0 a 1.0.3
> 
> ### Description
> App Version: 1.0.3
> 
> platform: win32 platformVersion: 10.0.22621 platformArchitecture: x64 cpuCount: 4 totalMem: 6018.0 MB freeMem: 839.3 MB
> 
> Error Type: [Render Context] Unhandled Rejection
> 
> Error: Error invoking remote method 'keychain-set': Error: Não há recursos de memória disponíveis suficientes para processar este comando.
> 
> ### Expected behaviour
> After entering a wallet's restore phrase, the error appears.
> 
> ### Actual behaviour
> After entering a wallet's restore phrase, the error appears.
> 
> ### Can the issue reliably be reproduced?
> Yes
> 
> ### Steps to reproduce the issue
> install open Begin setup skip third party wallets Iota Mainnet Restore Profile Recovery phrase Secure your profile Find your recovered accounts Give your profile a name Add a PIN number ERROR
> 
> ### Crash Status
> None of the above
> 
> ### Error Messages
> App Version: 1.0.3
> 
> platform: win32 platformVersion: 10.0.22621 platformArchitecture: x64 cpuCount: 4 totalMem: 6018.0 MB freeMem: 839.3 MB
> 
> Error Type: [Render Context] Unhandled Rejection
> 
> Error: Error invoking remote method 'keychain-set': Error: Não há recursos de memória disponíveis suficientes para processar este comando.
> 
> ### Error Logs
> _No response_
> 
> ### Profile Type
> Software (Stronghold)
> 
> ### Operating System
> Windows
> 
> ### Diagnostics
> ```shell
> App Version: 1.0.3
> 
> platform: win32
> platformVersion: 10.0.22621
> platformArchitecture: x64
> cpuCount: 4
> totalMem: 6018.0 MB
> freeMem: 839.3 MB
> 
> Error Type: [Render Context] Unhandled Rejection
> 
> Error: Error invoking remote method 'keychain-set': Error: Não há recursos de memória disponíveis suficientes para processar este comando.
> ```
> 
> ### Duplicate declaration
> * [x]  I have searched the issues tracker this issue and there is none
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Oi @pablo-hp, tudo bem?

Obrigado por reportar o problema!

De acordo com os relatórios enviados, a memória RAM disponível no seu sistema não é suficiente para os recursos utilizados pelo Bloom, tente liberar mais memória fechando algumas janelas de aplicativos ou também encerrando os que estão executando em segundo plano.
