### ISSUE TITLE
️🛠 - Fix alignment Table

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#2568]
### Task description

There is an alignment issue of the values on the right side with the Table component. E.g. in transaction details:

![image](https://github.com/bloomwalletio/bloom/assets/45079109/82840d42-2ba2-4cdb-a3bc-dce3afd9d769)

**Comment by MarkNerdi** [comment]
Fixed in
https://github.com/bloomwalletio/bloom-ui/pull/328
