### ISSUE TITLE
️🛠 - Fix minting NFTs on IOTA testnet

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#2594]
### Task description

Getting the following error when trying to mint an nft collection on IOTA testnet, it complained that the hrp was empty...
![Screenshot 2024-06-05 at 15 15 19](https://github.com/bloomwalletio/bloom/assets/89913787/1a24bc0d-1eb0-4848-8667-43b789e13030)

### Requirements

Fix issue with nft minting

**Comment by MarkNerdi** [comment]
Cannot reproduce this issue
@nicole-obrien  Is this still happening for you?

**Comment by nicole-obrien** [comment]
Yep couldn't reproduce again
