### ISSUE TITLE
️🛠 -  Update build actions before they are deprecated

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#2681]
### Task description

<img width="1354" alt="Screenshot 2024-06-28 at 11 21 17" src="https://github.com/bloomwalletio/bloom/assets/89913787/11ea3a64-4807-40aa-a83a-7a410ad014ca">

### Requirements

We need to update the build actions before things are deprecated and we can no longer build. See latest builds for warnings.

**Comment by MarkNerdi** [comment]
the reasons for these warnings were:
- `actions/create-release`: not maintained anymore
- `actions/upload-release-asset`: not maintained anymore
- `actions-rs/toolchain`: not needed anymore because we dont need rust
