### ISSUE TITLE
️🛠 - Move package to GitHub packages

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#307]
### Task description

We do not want to have the UI kit in the public npm library, so we can github packages to keep it private.

### Requirements

- Move package to Github packages
- Remove the public package
- Document how GH packages works
- Document how to use GH package
- Update CI?

**Comment by maxwellmattryan** [comment]
This has been done in [`ui-kit#51`](https://github.com/bloomwalletio/bloom-ui/issues/51).
