### ISSUE TITLE
️🛠 - Implement a L2 Transaction Summary Component

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#31]
### Description

Once L2 send flow is working, we need to show relevant L2 details to the users.

E.g.:

- Gas Price
- Gas Limit
- ...

### Requirements

TBD

### Checklist

- [X] I have linked the correct milestone and/or project(s)
- [X] I have added the appropriate labels
- [ ] I have assigned this task to the correct people

**Comment by MarkNerdi** [comment]
Already implemented in the new sendflow
