### ISSUE TITLE
️🛠 - Move activity logic into activity module

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#399]
### Task description

Currently we have all the logic related to activities in the wallet context. We should move it into its own module, so that its isolated from send or asset logic

### Requirements

- [ ] move activity logic into activity module

**Comment by maxwellmattryan** [comment]
@MarkNerdi I've approved the PR, but I added some changes so I'd like for you to give it one final round of testing before merging :pray:
