### ISSUE TITLE
️🛠 - Add Search to `Collection` tab

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#44]
### Description

Same as on the NFT tab, we need a search input to search through the collections.

### Requirements

- [x] Add Search Input on Collections Tab
- [ ] Search for collectionId or collectionName
- [x] Add search logic to only show collections which match the search value

### Checklist

- [X] I have linked the correct milestone and/or project(s)
- [X] I have added the appropriate labels
- [ ] I have assigned this task to the correct people

**Comment by jeeanribeiro** [comment]
closed by #2391
