### ISSUE TITLE
️🛠 - Hide/unhide NFTs in Collectibles gallery

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#45]
### Description

In the NFT details view, add a button to the menu to hide/unhide this NFT.
Hidden NFTs shouldnt be displayed in the gallery, related activities should still be shown.

### Requirements

- [ ] Impement hide/unhide button in NFT details view
- [ ] Hide NFTs in gallery

### Checklist

- [X] I have linked the correct milestone and/or project(s)
- [X] I have added the appropriate labels
- [ ] I have assigned this task to the correct people

**Comment by Tuditi** [comment]
Blocked by https://github.com/bloomwalletio/bloom/issues/46
