### ISSUE TITLE
️🛠 - Improve profile migrations

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#456]
### Task description

To improve readability and maintainability, we need to improve the structure of the profile migration logic. 
One thing we should do is to use single files for each migration (or bunch of migrations TBD).
Another thing would need to do is to store the profile version on the profiles themself, such that if a migration fails, and we release a new version with fixed migration, the profiles arent broken

### Requirements

- [ ] use single files for each migration
- [ ] store the profile version on the profiles

**Comment by nicole-obrien** [comment]
Already completed
