### ISSUE TITLE
️🛠 - Warning drawer when already connected to a dapp

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#470]
### Task description

When the user connects to a dapp twice, the already connected error is only logged in the console. Ideally we should have a pop-up that shows this warning to the user.

If the connection is deactivated, the user should be able to activate the connection

### Requirements

TBD

**Comment by nicole-obrien** [comment]
What if the user needs to reconnect to a dapp that Bloom thinks is connected, but the browser dapp has not persisted the session.
