### ISSUE TITLE
️🛠 - Better estimate the gas fee when we do not have enough L2 balance

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#474]
### Task description

If we don't have enough L2 balance and we are sending from L1 to an L2 address, the transaction will require gas, and currently we can not estimate the gas fee on the wasp node when we don't have enough balance for the transaction.

We need to find away to better estimate this fee, or allow the user to set it if we can not estimate it.

### Requirements

TBD once UX

**Comment by Tuditi** [comment]
Closed by https://github.com/bloomwalletio/bloom/pull/1268
