### ISSUE TITLE
️🛠 - Enabled signed build for Windows

### ISSUE THREAD

**Issue by maxwellmattryan** [bloomwalletio/bloom#481]
To ensure the authenticity and integrity of our Electron app for Windows, we need to sign the application with a valid code-signing certificate. This guide provides a step-by-step process to obtain a code-signing certificate and configure the GitHub Actions workflow for building the signed app.

##### 1. **Purchase a Code Signing Certificate:**
   - Purchase a Microsoft Authenticode code signing certificate from DigiCert.
   - Use the following link to buy the certificate: [DigiCert Microsoft Authenticode Code Signing](https://www.digicert.com/dc/code-signing/microsoft-authenticode.htm)

##### 2. **Generate a Certificate Signing Request (CSR):**
   - Use a tool like OpenSSL to create a CSR. The CSR is necessary for applying for a digital identity certificate from DigiCert.
   - Follow the steps in this tutorial to generate a CSR using OpenSSL: [How to generate a CSR using OpenSSL](https://www.sslshopper.com/what-is-a-csr-certificate-signing-request.html)

##### 3. **Submit the CSR to DigiCert:**
   - During the purchase process, submit the CSR to DigiCert.
   - DigiCert will verify the identity and issue a code-signing certificate upon approval.

##### 4. **Export the Certificate and Private Key:**
   - After receiving your certificate from DigiCert, you will need to export it, along with its private key, to a PFX file (.pfx or .p12). A PFX file bundles a private key and certificate together and is used for secure storage and transportation of cryptographic information.
   - You can use OpenSSL to combine your certificate and private key into a single .pfx file.
   - Example Command:

```bash
openssl pkcs12 -export -out certificate.pfx -inkey privateKey.key -in certificate.crt
```

This command will create a .pfx file from your private key (privateKey.key) and certificate (certificate.crt). You will be prompted to create a password, which is used to protect the .pfx file.

For more information about exporting a certificate and private key, refer to the OpenSSL documentation: [OpenSSL PKCS#12 Command Options](https://www.openssl.org/docs/manmaster/man1/openssl-pkcs12.html)

##### 5. **Encode the Certificate in Base64 Format:**
   - Convert the .pfx certificate file to base64 format using the following command:
     ```bash
     base64 /path/to/your/certificate.pfx
     ```
   - Copy the base64 output.

##### 6. **Add Secrets to GitHub Repository:**
   - Go to the GitHub repository settings.
   - In the "Secrets & tokens" section, add the following secrets:
     - `WIN_CERT_BASE64`: Paste the base64-encoded certificate here.
     - `WIN_CERT_PASSWORD`: Enter the password used to protect the certificate file.

**Comment by nicole-obrien** [comment]
Purchased a DigiCert EV certificate today, awaiting company verification.

**Comment by nicole-obrien** [comment]
For EV verification we need to be listed on a well known online directory with our phone number. Awaiting for verification of our business with yell.com now. Before they can complete this one.

**Comment by nicole-obrien** [comment]
After many listings they would not accept the company information without a letter from a lawyer or accountant, and more ID. This was provided first thing yesterday, still waiting for them to respond.
