### ISSUE TITLE
️🛠 - Fix loading chunk exception on packaged builds

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#497]
### Task description

Currently getting this exception when opening the signed packaged app on mac and linux:
![Screenshot 2023-08-24 at 22 21 10](https://github.com/bloomwalletio/bloom/assets/89913787/98fc2266-8d13-40b6-ba5a-1e31d8cec23d)

### Requirements

Find and fix the issue so this does not occur

**Comment by jeeanribeiro** [comment]
The issue is caused by `bloom-ui` `locales` and `svg` dynamic imports and `flowbite` dependency

**Comment by jeeanribeiro** [comment]
`locales` and `svg` are now statically imported in  `bloom-ui`

**Comment by jeeanribeiro** [comment]
Task tracker for removing `flowbite` dependency: https://github.com/bloomwalletio/bloom-ui/issues/79
