### ISSUE TITLE
Fix claim in transaction id/link not showing in activity popup

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#888]
### Task description

![Image](https://github.com/bloomwalletio/bloom/assets/89913787/2084644c-7fdd-430b-bc12-be9437e5f21e)

### Requirements

The claiming transaction id is not showing in the activity popup

**Comment by MarkNerdi** [comment]
Fixed in https://github.com/bloomwalletio/bloom-ui/pull/199

**Comment by MarkNerdi** [comment]
Fixed after releasing uikit 0.16.11
