### ISSUE TITLE
️🛠 - Fix alignment of breadcrumbs

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#891]
### Task description

![Image](https://github.com/bloomwalletio/bloom/assets/89913787/d0be1273-b9de-461c-bd9c-8ff028b7052c)

### Requirements

Alignment of breadcrumbs seems to have broken, and we should fix

**Comment by MarkNerdi** [comment]
Fixed in https://github.com/bloomwalletio/bloom-ui/pull/208
