### ISSUE TITLE
️🛠 - Remove unused locales

### ISSUE THREAD

**Issue by maxwellmattryan** [bloomwalletio/bloom#94]
### Description

These files contain lots of unused and they should be removed

### Requirements
- remove unused locales, being careful to not remove locales that are programmatically included

### Checklist

- [ ] I have linked the correct milestone and/or project(s)
- [X] I have added the appropriate labels
- [X] I have assigned this task to the correct people

**Comment by Tuditi** [comment]
https://github.com/bloomwalletio/bloom/pull/662
